### ISSUE TITLE
Version of kornia

### ISSUE THREAD

**Issue by ccj5351** [XiSHEN0220/RANSAC-Flow#1]
Can I get to know which version of kornia are you using for this project? Based on the Readme, you are using PyTorch=1.2, right? Thanks!

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest in our project!!!
Yes, it should work with Pytorch1.2. 
Other dependencies are:
kornia==0.1.4.post2
opencv-python==3.4.2.17
scipy==1.2.0

I will do an update soon (after Nips Deadline). It should have more doc + fix some bugs.

**Comment by ccj5351** [comment]
Thanks a lot!
