### ISSUE TITLE
yfcc evaluation using sift 

### ISSUE THREAD

**Issue by panxkun** [XiSHEN0220/RANSAC-Flow#10]
Hi, appreciate your work very much!
I have trouble again reproducing the result in your paper. In YFCC eval, your code only get the acc result using flow, but now I want to use the sift method to test my code to ensure it is right, my code was mainly modified on your code. I get the result in this paper: 
![微信图片_20210222231445](https://user-images.githubusercontent.com/44204704/108727880-f9e9e700-7563-11eb-8b74-71b155bcaf95.png)
the main code as follow:
![1614007137(1)](https://user-images.githubusercontent.com/44204704/108728536-a88e2780-7564-11eb-98ee-e9443d5eae3b.png)
the function in this code are all copy from your script. maybe I wrongly use some parameters like ransac threshold or matcher, could you please tell me some detail about this evalution?

**Comment by fdarmon** [comment]
Hi, 

If I remember correctly, the results on the paper were obtained with 2000 SIFT features. We used ratio test with ratio 0.8 and also bidirectional check. 

François

**Comment by panxkun** [comment]
thanks, it works!
