### ISSUE TITLE
Flow image

### ISSUE THREAD

**Issue by LiuShihHung** [XiSHEN0220/RANSAC-Flow#11]
Hi, your work is amazing, I want to ask how to show the flow image in evaluation or in demo.ipynb.

Thanks!

**Comment by XiSHEN0220** [comment]
Hi, 
Thank you for your interests in our project!!! 
To visualize the flow, you can try [this cool repo](https://github.com/tomrunia/OpticalFlow_Visualization), which visualises flow as an RGB image. 

Hope it helps, 

Best, 

Xi

**Comment by XiSHEN0220** [comment]
Hi, 
Thank you for your interests in our project!!! 
To visualize the flow, you can try [this cool repo](https://github.com/tomrunia/OpticalFlow_Visualization), which visualises flow as an RGB image. 

Hope it helps, 

Best, 

Xi

**Comment by LiuShihHung** [comment]
Hi, thanks for your reply!
I can show the flow image now! 
thank you!!

**Comment by TheRealPoseidon** [comment]
> Hi, thanks for your reply! I can show the flow image now! thank you!!

Hi, may I ask you a question about visulization? 
After I tried [Evaluation on Two-View Geometry Estimation](https://github.com/XiSHEN0220/RANSAC-Flow/tree/master/evaluation/evalYFCC#segnet--wo-fine-tuning), some .npy files are stored. Some .npy are in shape of (x1,x2,x3.x4), while others are in shape of (x1,x2). I want to ask how to visualize them.
Thanks!
