### ISSUE TITLE
align

### ISSUE THREAD

**Issue by shang-sxc** [XiSHEN0220/RANSAC-Flow#12]
Hello!I want to use your code to align my image. The image is not complicated and has few textures. Do you also need to build 20000 pairs of data sets in the 100 scenarios mentioned in the article?

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest in our project! 

I would suggest firstly aligning your images with our pre-trained model.
A demo can be found [here](https://github.com/XiSHEN0220/RANSAC-Flow/blob/master/quick_start/demo.ipynb). 

Note that, one needs to install [these packages](https://github.com/XiSHEN0220/RANSAC-Flow#21-dependencies). 

 If it doesn't work well, you could try to generate your own training pairs and perform [fine-tuning on your data](https://github.com/XiSHEN0220/RANSAC-Flow#43-fine-tuning-on-your-own-dataset).

Hope it helps, 

Best, 

Xi

**Comment by shang-sxc** [comment]
Thanks.In fine alignment, the remaining feature matching points that are not well aligned are re aligned to get the homography matrix through coarse alignment. Can I take out the code of fine alignment and use it alone. Because I have a rough alignment method, I don't know if it is feasible?

**Comment by XiSHEN0220** [comment]
Yes, sure. You can use the fine alignment alone.
Note that the maximum displacement predicted by the fine alignment model is 24 pixels.

**Comment by shang-sxc** [comment]
Is fine alignment independent of coarse alignment? I thought fine alignment was involved in the process of iteration and coarse alignment was involved. Thank you very much.

**Comment by XiSHEN0220** [comment]
Hi, 

Yes, they are independent.
You can just apply the model of the fine alignment if your pairs are already coarsely aligned.   

Best, 

Xi

**Comment by jia199903** [comment]
> 请注意，精细对齐模型预测的最大位移为 24 像素。

请问为什莫是24呢
