### ISSUE TITLE
cant download pretrained model

### ISSUE THREAD

**Issue by yqyang9464** [XiSHEN0220/RANSAC-Flow#13]
Hi! I want to use your pre-trained model to align my image. But something wrong when I download it by bash 'download_model.sh', It is said that the link has been reset. Could you please provide the latest download link? thank you very much

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest in our project!!

I've checked the download link, it is still validated. 
The reason might be that  Dropbox is blocked in China.
You can try VPN or give me your personal email, I can send you the pretrained models. 

Hope it helps, 

Best

Xi

**Comment by yqyang9464** [comment]
VPN works， thank you very much
