### ISSUE TITLE
How to improve inference speed?

### ISSUE THREAD

**Issue by USTC-wlsong** [XiSHEN0220/RANSAC-Flow#15]
Thank for your open source code.  When i run the demo by a single GPU GeForce GTX 1080Ti(12G) , the speed is very slow, coarse fine for 2.56s, the whole process is about 4.31s.  Can you give me some suggestions to shorten this inference time?

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest in our project!! 

The demo is slow, as one needs to initialize the models, and put them to GPU.
The inference should be faster on a larger test dataset. 

Something you can try to reduce the inference time: 
1. one can definitely use fewer iterations in RANSAC **[In [4] in the demo, coarseIter]**
2. if one knows in advance that the input pairs are with a similar viewpoint, the nb of scales **[In [4] in the demo, nbScale]** and scale ratio **[In [4] in the demo, scaleR]** can be reduced.
3. image size has an impact as well **[In [4] in the demo, minSize]**, larger image size leads to heavier computational time for both coarse and fine alignment. 

Additionally, it might be more efficient to use a deep model for the homography estimation, such as [this repo](https://github.com/mazenmel/Deep-homography-estimation-Pytorch). If it works, everything could be paralleled in GPU, which should be much more efficient. I am not an expert in this domain, more advanced methods have been probably published. If you are interested in this direction, you could check recent publications. 

Hope it helps !! 

Best, 
Xi

**Comment by USTC-wlsong** [comment]
Thank you for your patience, this nanny-level tutorial really touched me! Since I have been busy revising the paper recently, I cannot reply in time, please forgive me! In the next step, I will follow your specific suggestions for relevant experimental verification. If possible, I would like to maintain close communication with you via email. My mail address is wlsong@mail.ustc.edu.cn
I wish you success in studying abroad and in scientific research!!
Best,
Wlsong
