### ISSUE TITLE
obtain transformation matrix

### ISSUE THREAD

**Issue by Camilochiang** [XiSHEN0220/RANSAC-Flow#19]
Great network! Thanks for the code.
For registration you reduce the size of the image, but to save this images i would like to keep the original resolution. How can I obtain the transformation matrix? Sorry if is a trivial question but i dont find it.Thanks!

**Comment by XiSHEN0220** [comment]
Hi, 

If I understand correctly, you want to get the optical flow. 
The flow can be obtained [here](https://github.com/XiSHEN0220/RANSAC-Flow/blob/master/model/model.py#L236)

You can also refer to the [notebook](https://github.com/XiSHEN0220/RANSAC-Flow/tree/master/quick_start) for visualization.
