### ISSUE TITLE
The link of pretrained-model failed

### ISSUE THREAD

**Issue by ngx2333** [XiSHEN0220/RANSAC-Flow#21]
Thanks for the open code!
I notice that the url link "https://www.dropbox.com/s/uegv8aqq5sj3542/model.zip" is failed,could you upload the pretrained-model again or update the link?

**Comment by XiSHEN0220** [comment]
Hi, Thanks for your interest in our work! 

The link works normally in my case.
You might need a VPN to access Dropbox if you are in some particular regions. 
Or I could send you via Google Drive if you could provide your email address. 

Best, 

Xi

**Comment by ngx2333** [comment]
> 
Very sorry,it is my fault.Everything is ok when I switch the VPN.
Thanks again for the interesting and useful work!
