### ISSUE TITLE
Training with smaller kernel

### ISSUE THREAD

**Issue by Camilochiang** [XiSHEN0220/RANSAC-Flow#22]
Hei. When trying smaller kernel with the actual weights I get deformation in the images. that is clear as the actual weights were trained with kernel of size 7. I would like to train with smaller kernel to get better alignment. How long did you train in stage 1? my calculations say that with a simple GPU 16 RAM will take me 1.4 days to run 200 epochs

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest!

In my experiments, smaller kernels give slight worse results. 
But if you train on your own dataset, the conclusion might be different. 

I don't remember the exact training time, but 1.4 days seems to be normal. 

Hope it helps, 

Best, 

Xi
