### ISSUE TITLE
Missing idx_mat output from matches_from_flow

### ISSUE THREAD

**Issue by joel7t** [XiSHEN0220/RANSAC-Flow#3]
When trying to run [`evalYFCC/get_ply.py`](https://github.com/XiSHEN0220/RANSAC-Flow/blob/master/evaluation/evalYFCC/get_ply.py#L287), it calls the function `compute_and_save` located in [`evalYFCC/run_point_cloud.py`](https://github.com/XiSHEN0220/RANSAC-Flow/blob/master/evaluation/evalYFCC/run_point_cloud.py#L166).  The function `compute_and_save` expects 3 outputs from [`matches_from_flow`](https://github.com/XiSHEN0220/RANSAC-Flow/blob/master/evaluation/evalYFCC/getResults.py#L53), however only 2 are provided.

```
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by fdarmon** [comment]
Thank you for pointing it out, we mistakenly added those files but they are not used for any evaluation in the paper. You may use these functions but, as you noticed, there are some mistake and we cannot guarantee any results.
