### ISSUE TITLE
Off-the-shelf features for the coarse parametric alignment

### ISSUE THREAD

**Issue by rcg12387** [XiSHEN0220/RANSAC-Flow#6]
Hi
You wrote in your paper like this: "We use off-the-shelf deep features (conv4 layer of a ResNet-50 network) to obtain
these correspondences."
And in coarseAlignFeatMatch.py you implemented like this:
```
resnet_feature_layers = ['conv1','bn1','relu','maxpool','layer1','layer2','layer3']
... ... 
resnet_module_list = [getattr(resNetfeat,l) for l in resnet_feature_layers]
last_layer_idx = resnet_feature_layers.index('layer3')
self.net = torch.nn.Sequential(*resnet_module_list[:last_layer_idx+1])
```
What do you mean exactly about "conv4 layer of a ResNet-50 network"?

**Comment by XiSHEN0220** [comment]
Hi, 
The output of the Layer3 is the so-called _Conv4_ feature.
The feature map of the 4th convolutional layer (block): conv1, layer1, layer2, layer3

**Comment by rcg12387** [comment]
Hi
Yeah, you as the author regard "Conv4" of the paper as it points the "layer3".
But I and others as readers do not directly accept that "Conv4" means the "layer3" because layer1 and layer2 and layer3 also have many conv layers, e.g. layer1 has 9 conv layers.
It may mislead readers about your "Conv4" as the fourth convolution layer, which is not.
Besides there are other typos in your paper: in Table 2 "ous" which you might intend to write as "ours".
Anyway, your work is very nice and I learned much from your work.
Thank you.
