### ISSUE TITLE
Aachan localization

### ISSUE THREAD

**Issue by PruneTruong** [XiSHEN0220/RANSAC-Flow#8]
Hi, very nice repo ! Are you planning on giving the code you used to submit results for Aachen evaluation ? 
Thanks !

**Comment by XiSHEN0220** [comment]
Hi, Prune, 

This part of code is more complicated + need to install other dependencies. 
But I could prepare it after the CVPR deadline. 

Best, 

Xi

**Comment by PruneTruong** [comment]
Actually, I ended up implementing part of the pipeline myself. However, would you mind making your results public on the submission website, or give me the updated metrics ?  Indeed, in May, they changed the accuracy of the poses of the query images, and changed the thresholds of evaluation, and therefore the results stated in publications are not comparable anymore with the submission results.  Thanks a lot !

**Comment by XiSHEN0220** [comment]
@PruneTruong 
This is what I obtained with Moco / INet feature.
![image](https://user-images.githubusercontent.com/11667167/97973109-ddb01780-1dc5-11eb-88fd-3299f80093a7.png)

The GitHub has been updated, see [here](https://github.com/XiSHEN0220/RANSAC-Flow/tree/master/evaluation/evalAachan) for the same results. 

Hope it helps. 

Best, 

Xi

**Comment by PruneTruong** [comment]
Great, thanks ! I am closing the issue

**Comment by jiangwei221** [comment]
Hi Xi:
This is a great work, thanks for releasing it!
I have a question about the Aachen localization. The paper stated "first compute image matching for a list of image pairs and then give them as input to COLMAP [72] that provides a localisation estimation for the queries"
I don't understand how do you get the absolute pose? How do you convert the 2D-to-2D correspondences to 2D-to-3D correspondences?
If you can make one entry to be public that would be very helpful.
