### ISSUE TITLE
Question about reproduce the evaluation result of other method in evalCorr

### ISSUE THREAD

**Issue by panxkun** [XiSHEN0220/RANSAC-Flow#9]
Hi, very nice repo!
Now i want to get the evaluation result in sparse correspondence experiment. I follow the protocol in the script /evaluation/evalCorr/getResults.py to test other dense matching method like glu-net, but there is a large gap between the result I got and yours in paper. In your code, your method can get the match file(name ‘mask_{:d}_{}H.npy’), then a threshold default set 0.95 is used to get the matchability, but in other method like glu-net, we can only get the flow between two images, I guess it make the difference using other method. I want to know the way you evaluate other method which only output a flow from the network.

**Comment by XiSHEN0220** [comment]
Hi, thanks for your interest in our projects!! 
Here is a simple way to do: 
As you have the flow, you can forget about the homograpy. 
You can evaluate directly the flow with this [line](https://github.com/XiSHEN0220/RANSAC-Flow/blob/master/evaluation/evalCorr/getResults.py#L283) 

Hope it helps, 

Best
-Xi

**Comment by panxkun** [comment]
but how can I deal with the param `match2` in function `alignmentError`

**Comment by XiSHEN0220** [comment]
As you don't have matchability term, you can set it to 1 for all the pixels (which means every pixel is matchable). 
For example: match2 = np.ones((h,w))

**Comment by panxkun** [comment]
Appreicate your advice！
Now I can get the same result after I solve above problems
